# Punto uno

**Instrucción**

Imprimir un listado con los números del 1 al 100 cada uno con su respectivo cuadrado.

In [3]:
x:int#Se declara la variable x, especificando que es de tipo int (dado a que el programa funciona con números enteros)
x=1#Se inicializa a x en 1, ya que el listado debe empezar con este número

while x<=100:#Se ejecuta el bloque mientras x sea menor o igual a 100 (dado a que el listado debe llegar hasta 100)
    cuadrado=x**2#Se halla x elevado a la dos
    print(x, cuadrado, sep=", ")#Se imprimen los valores de x y de x al cuadrado, usando el parámetro separador
    x+=1#x se incrementa una unidad para reiniciar el ciclo hasta que no se cumpla la condición de x<=100

1, 1
2, 4
3, 9
4, 16
5, 25
6, 36
7, 49
8, 64
9, 81
10, 100
11, 121
12, 144
13, 169
14, 196
15, 225
16, 256
17, 289
18, 324
19, 361
20, 400
21, 441
22, 484
23, 529
24, 576
25, 625
26, 676
27, 729
28, 784
29, 841
30, 900
31, 961
32, 1024
33, 1089
34, 1156
35, 1225
36, 1296
37, 1369
38, 1444
39, 1521
40, 1600
41, 1681
42, 1764
43, 1849
44, 1936
45, 2025
46, 2116
47, 2209
48, 2304
49, 2401
50, 2500
51, 2601
52, 2704
53, 2809
54, 2916
55, 3025
56, 3136
57, 3249
58, 3364
59, 3481
60, 3600
61, 3721
62, 3844
63, 3969
64, 4096
65, 4225
66, 4356
67, 4489
68, 4624
69, 4761
70, 4900
71, 5041
72, 5184
73, 5329
74, 5476
75, 5625
76, 5776
77, 5929
78, 6084
79, 6241
80, 6400
81, 6561
82, 6724
83, 6889
84, 7056
85, 7225
86, 7396
87, 7569
88, 7744
89, 7921
90, 8100
91, 8281
92, 8464
93, 8649
94, 8836
95, 9025
96, 9216
97, 9409
98, 9604
99, 9801
100, 10000